# Generated by Django 5.1.1 on 2024-10-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'statistics',
                'db_table': 'statistic',
                'ordering': ['-id'],
            },
        ),
    ]
