# Generated by Django 5.1.1 on 2024-10-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
