# Generated by Django 5.1.1 on 2024-10-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'colors',
                'db_table': 'color',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItemBalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('can_be_cheaper', models.BooleanField(default=False)),
                ('income_price_usd', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('income_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('selling_percentage', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'document item balances',
                'db_table': 'doc_item_balance',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('can_be_cheaper', models.BooleanField(default=False)),
                ('income_price_usd', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('income_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
                ('selling_percentage', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'document items',
                'db_table': 'doc_item',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=4)),
            ],
            options={
                'verbose_name_plural': 'documents',
                'db_table': 'document',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('barcode', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'items',
                'db_table': 'item',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'units',
                'db_table': 'unit',
            },
        ),
    ]
