# Generated by Django 5.1.1 on 2024-10-06 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder_app', '0002_initial'),
        ('currency_app', '0002_initial'),
        ('product_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentitembalancemodel',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_item_balances', to='currency_app.currencymodel'),
        ),
        migrations.AddField(
            model_name='documentitembalancemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_item_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentitemmodel',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_items', to='currency_app.currencymodel'),
        ),
        migrations.AddField(
            model_name='documentitemmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentitembalancemodel',
            name='doc_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='product_app.documentitemmodel'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='builder_app.buildermodel'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentitemmodel',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_app.documentmodel'),
        ),
        migrations.AddField(
            model_name='documentitembalancemodel',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_item_balances', to='product_app.documentmodel'),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.colormodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_app.categorymodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.companymodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.itemmodel'),
        ),
        migrations.AddField(
            model_name='documentitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_items', to='product_app.itemmodel'),
        ),
        migrations.AddField(
            model_name='documentitembalancemodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_item_balances', to='product_app.itemmodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.unitmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcolor',
            unique_together={('item', 'color')},
        ),
    ]
